- name: printing playbook vars
  hosts: alma1
  vars:
    username: muna
    a: apple
  tasks:
  - name: printing vars using debug module
    debug:
      msg: |
        "the username is {{username}}"
        {{a}}
